---
title: "Formal Statement Problem: Analysis on CFPB'S Consumer Complaints Open Dataset"
author: "Alison Jing Huang"
date: "4/9/2018"
output: html_document
---

### Objective and Motivation
We all have long term relationships with financial institutions from having checking/savings account to owning private loans. With so many options of  insitutions and various products available on the market, choosing a ideal firm with top-notch customer service is essential for Americans to feel at ease in the decade followed by the 2007-2008 financial crisis and the Great Recession.

I choose this project because I was interested in learning how financial institutions measure customer satsifactions, one of the metrics is how quickly they can resolve a customer's complaint. Financial insituitions could better understand the factors contributing to complaints instead of resolving complaints one-by-one.The dataset will also help shape firms' image in the marketplace as well as identify new risks for the financial insitutions and present new opportunities.With a data-driven, enterprise-wide view of their internal complaint data, firms could potentially better address their regulatory compliance responsibilities and elevate their customer experience and operational effectiveness, and prevent the escalation of higher level of regulatory and reputational risk.

An in-depth analysis using Data Science and Machine Learning techniques will help uncover some insight associated with the consumer complaint data and help insitutions measure customer satsifactions and help Financial Product/Service managers effectively give the appropriate responses to the complaints.  


### Background

The **`Consumer Financial Protection Bureau(CFPB)`** was a U.S government agency established under the **Consumer Protection Act**, also known as *Dodd-Frank Wall Street Reform Act* in July 2010. Its core mission is to watch out for American consumers in the market for consumer products and services, it would heighten government accountability by consolidating in one place responsibility of supervision and enforcement with respect to laws, and protect families from unfair, deceptive, and abusive financial practices.Its jurisdiction includes banks, credit unions, securities firms, payday lenders, mortage-servicing operations, foreclosure relief services, debt collections, and other financial companies operating in the United States. 

#### **The CFPB's primary focus includes**:

* Rooting out unfair, deceptive, or abusive acts or pratices by writing rules, supervising companies, and enforcing the law
* Enforcing laws that outlaw discrimination in consumer finance
* Taking consumer complaints
* Enhancing financial education
* Researching the consumer experience of using financial products
* Monitoring financial markets for new risks to consumers.

Each week CFPB sends out thousands of consumers' complaints regarding financial products and services to companies for responses, those complaints are then published online in the [Consumer Complaint Database](https://www.consumerfinance.gov/data-research/consumer-complaints/)  ranging from *mortage*, *debt collection*, *credit reporting/repairing services*, *bank account*, *student loans*, *consumer loans*, to *credit card/prepaid card*, *money transfer/virtual currency*, *vehicle lease*,...etc. Consumer complaints are added to this public database after the company has responded to the complaint, confirming a commerical relationship with the consumer, or after 15 calender days of the initial complaint date. On average 97% of complaints sent to companies get timely responses. 

The Bureau's organizational structure consists of Office of Technology & Innovation led by **Jerry Horton**, *The Chief Information Officer* and data research and analysis teams for data analysis, the result finding will then be reported/conveyed to *The Office of Consumer Response* led by **Christopher Johnson**, and can be recommended to mid-senior level managers of major U.S Financial Institutions, bank stakeholders and other consumer regulatory agencies. As a (hypothetical) Data Science intern, I am assigned to work on one portion of the open dataset during a time range, to identify patterns in the data measuring improvements and detecting product service areas in need of improvement.

### Dataset Description

The datset is publicly available on [Data.gov](https://catalog.data.gov/dataset/consumer-complaint-database) and can be downloaded in `csv` format. It contains the list of consumer complaints received by CFPB about financial product services offered by banks and other financial insitutitions across the United States from December 2011 to April, 2018.
**There are 18 attributes contained in the data set:**

1. **Date received**	**---** The CFPB received the complaint
2. **Product**	**---** The type of product the consumer identified in the complaint
3. **Sub-product**	**---** The type of sub-product the consumer identified in the complaint
4. **Issue**	**---** The issue the consumer identified in the complaint
5. **Sub-issue** **---** The sub-issue the consumer identified in the complaint
6. **Consumer complaint narrative** **---** The consumer-submitted description of "what happened" from the complaint
7. **Company public response** **---** The company's optional, public-facing response to a consumer's complaint
8. **Company** **---** The complaint is about this company	
9. **State**  **---** The state of the mailing address provided by the consumer
10. **ZIP code** **---** The mailing ZIP code provided by the consumer	
11. **Tags** **---** Data that supports easier searching and sorting of complaints submitted by or on behalf of consumers.	
12. **Consumer consent provided?** **---** Identifies whether the consumer opted in to publish their complaint narrative.	
13. **Submitted via** **---** How the complaint was submitted to the CFPB. For example, "Web" or "Phone"
14. **Date sent to company** **---** The date the CFPB sent the complaint to the company
15. **Company response to consumer** **---** This is how the company responded.	
16. **Timely response?** **---** Whether the company gave a timely response.
17. **Consumer disputed?** **---** Whether the consumer disputed the company's response	
18. **Complaint ID** **---** The unique identification number of a complaint


### Success metrics
One major used industry metrics for measuring consumer satisfaction is to look at how consumer complaints are resolved over time.If the institution is able to have lower than average dispute percentage across the board compared to others, it's a success indicator that the customers are more satisfied in that firm. Another success metrics is to be able to identify the major issues of each product service and develop solutions/recommendations of tackling them. 

### Estimated risks
Since the data only contains complaints submitted to the CFPB, it is unlikely that the data fully reflects a financial insitution's own complaint records, therefore the result may not necessarily reflect the insitution's current state.


### Proposed project timeline
1. Data Cleaning and Exploratory Data Analysis --- This will take 7 days (1 week)

2. Potentially utilize *RShiny* package for Data Visualization --- This will take 3 days

3. Research and perform ML modeling  --- This will take 2 weeks






